#ifndef EXITCODES
#define EXITCODES

#define MALLOC_ERR_EXIT_CODE -1
#define GENERAL_ERR_CODE -2
#define INVALID_TOKEN_ERROR_CODE -3
#define DIVISION_BY_ZERO_ERR_CODE -4
#define BAD_ARG_ERR_CODE -5
#define INVALID_FILE_PATH_ERR_CODE -6
#define UNBALANCED_PARENTHESIES_ERR_CODE -7

#define MALLOC_ERR_MSG "Malloc error"
#define GENERAL_ERR_CODE_MSG "An error occured"

#endif
